### PR TITLE
Add support for Iterable 

### PR DESCRIPTION
**Pull request by verhasi**
The Collection interface is already supported. Similar support needed for the Itarable interface as well.

### CODE REVIEW

**Comment by verhasi** [comment]
Thank you for fixing the javadoc :)

**Comment by tobiasstamann** [comment]
I will trigger a minor release now

**Comment by tobiasstamann** [comment]
And thanks for moving some code to java 8 :) 

It's still something i need to do

**Comment by verhasi** [comment]
@tobiasstamann By the way, do you/the project have/has any code style preference?  I usually use IDEA, so getting a code-style XML to apply would be beautiful.

**Comment by tobiasstamann** [comment]
I am using IDEA as well, even if it doesn't work with those annotation processor projects that well.
Mostly using the default code style scheme, but could explicitly add one to the project. 



Your change has been released now with version 0.23.0.

**Pull request merged**
